# Generated by Django 3.2.16 on 2022-10-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('check_type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], default='client', max_length=7)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], default='client', max_length=7)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('pdf_file', models.FileField(upload_to='media/pdf')),
                ('printer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipt.printer')),
            ],
        ),
    ]
