# Generated by Django 3.2.16 on 2022-10-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='id',
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
