# Generated by Django 3.2.16 on 2022-10-08 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_printer_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
