# Generated by Django 3.2.16 on 2022-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_auto_20221008_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
